### ISSUE TITLE
Social Media Buttons in the footer

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack-www#107]
(suggested by @IvetPM from ML)

As for the icons - I suggest we get some from freepik or Fontawesome?
Please see these:
https://fontawesome.com/icons/linkedin?f=brands&s=solid
https://fontawesome.com/icons/square-twitter?f=brands&s=solid
https://fontawesome.com/icons/youtube?f=brands&s=solid
https://fontawesome.com/icons/square-github?f=brands&s=solid

**Comment by prernadabi23** [comment]
Hello, @rohityadavcloud Can I solve this issue?

**Comment by rohityadavcloud** [comment]
Hi @prernadabi23 thanks for volunteering. I’m yet to gather the links, might be easier for me to do this. If you figure out early though go ahead raise a PR against docusauras-staging branch.

**Comment by rohityadavcloud** [comment]
Fixed in 22739e104a1d453a1dfdff84248ca1c90e5a526d
