### ISSUE TITLE
[Blog] Full articles content is displayed on the listings

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack-www#111]
On https://blogs.apache.org/cloudstack/ the listings include a reduced view of the articles and a Read More button to get the full content on each article

**Comment by rohityadavcloud** [comment]
Ivet has suggested the same, thanks @nvazquez we can look into that. One way is to add a truncate option. I'm working on docs here: https://cloudstack.staged.apache.org/website-guide

**Comment by rohityadavcloud** [comment]
I've added a few truncate options to recent posts.

**Comment by rohityadavcloud** [comment]
Fixed by 2859b2581d6cfc621b318f8bf30e97e4ed51a83e
