### ISSUE TITLE
[Blog] Minor visual issues

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack-www#113]
- REGISTER NOW button is next to the heading at:
   - https://cloudstack.staged.apache.org/blog/meet-apache-cloudstack-at-kubecon/ 
   - https://cloudstack.staged.apache.org/blog/cloudstack-european-user-group-may
- Separation missing on between the first talks and authors on: https://cloudstack.staged.apache.org/blog/cloudstack-collaboration-conference-2022-roundup
- Missing image on: https://cloudstack.staged.apache.org/blog/cloudstack-european-user-group-virtual/
- Images sizes: https://cloudstack.staged.apache.org/blog/what-s-new-in-apache

**Comment by rohityadavcloud** [comment]
- ~~REGISTER NOW button is next to the heading at:~~
   - ~~https://cloudstack.staged.apache.org/blog/meet-apache-cloudstack-at-kubecon/~~
   - ~~https://cloudstack.staged.apache.org/blog/cloudstack-european-user-group-may~~
- Separation missing on between the first talks and authors on: https://cloudstack.staged.apache.org/blog/cloudstack-collaboration-conference-2022-roundup
- Missing image on: https://cloudstack.staged.apache.org/blog/cloudstack-european-user-group-virtual/
- ~~Images sizes: https://cloudstack.staged.apache.org/blog/what-s-new-in-apache~~

@nvazquez I've addresse some of them, I don't see missing image and what you mean by separation comment.

**Comment by rohityadavcloud** [comment]
Thanks Nicolas, I've addressed that. For the image, I think it's not useful as the header has the same info and I'm struggling to get it on the left side. I'll ask Ivet if we need more thorough 1:1 review of all posts.
