### ISSUE TITLE
[Blog] Missing articles on News category

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack-www#114]
https://cloudstack.staged.apache.org/blog/tags/news lists only 16 articles, however there many articles missing from: https://blogs.apache.org/cloudstack/category/News

**Comment by rohityadavcloud** [comment]
Thanks @nvazquez I'll keep it open for now, I think news as category has been mixed with announcements; you'll actually see more in announcement category (related to project releases, cve posts which were wrongly tagged as news).

**Comment by rohityadavcloud** [comment]
I'll discuss with Ivet, I've fixed most of the posts manually with a rule that anything project release related is announcement, otherwise meetups, conferences etc are under news. Thanks @nvazquez
