### ISSUE TITLE
Google search result for `Apache CloudStack` says `No information is available for this page.`

### ISSUE THREAD

**Issue by jbampton** [apache/cloudstack-www#181]
When you search for `Apache CloudStack` with Google it returns the CloudStack website as the first result but seems we have some missing information or misconfiguration.

Under the link heading it says: `No information is available for this page.`

Seen in the image below:

![google-search-results-for-apache-cloudstack](https://github.com/apache/cloudstack-www/assets/418747/b0341f8e-9d9e-42b4-8f56-3b8fc78b60c1)

**Comment by rohityadavcloud** [comment]
Thanks for reporting @jbampton I don't know what to change in the website to make an effect for the homepage. Any thoughts, or idea? cc @DaanHoogland @vishesh92

**Comment by vishesh92** [comment]
Description in search results in fetched from the `meta` tag.
Ref.: https://developers.google.com/search/docs/appearance/snippet

Docusaurus has support for this - https://docusaurus.io/docs/seo
Let me try to get this fixed by next week.

**Comment by DaanHoogland** [comment]
@vishesh92 I have done some experimenting as i got signalled on this off-line. three methods (including the one you mention above) but nomne have worked so far. Can you see what is wrong there: #195?
cc @rohityadavcloud @jbampton

**Comment by vishesh92** [comment]
@DaanHoogland I was wrong. I can see the description on other search engines. This is happening because of robots.txt.

**Comment by vishesh92** [comment]
@DaanHoogland I have created a PR here to use different robots.txt while building the main branch
https://github.com/apache/cloudstack-www/pull/196

**Comment by DaanHoogland** [comment]
merged, let's check the coming days how this pans out

**Comment by vishesh92** [comment]
This is fixed now. Closing the issue.

![image](https://github.com/apache/cloudstack-www/assets/8760112/e0063e2a-342f-4529-b947-55ad19fb7921)
